<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="ClickHouse.Client" />
    <PackageReference Include="Dapper" />
    <PackageReference Include="Microsoft.Extensions.Http" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\PluginsCore\Hamstix.Haby.Shared.PluginsCore.csproj" />
  </ItemGroup>

</Project>
