<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="KubernetesClient" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\PluginsCore\Hamstix.Haby.Shared.PluginsCore.csproj" />
  </ItemGroup>

</Project>
