<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Authentication" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" PrivateAssets="all" />
    <PackageReference Include="Grpc.Net.ClientFactory" />
    <PackageReference Include="Grpc.Net.Client.Web" />
    <PackageReference Include="Google.Protobuf" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Shared\Hamstix.Haby.Shared.csproj" />
  </ItemGroup>

</Project>
