<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <None Remove="Protos\configuration.proto" />
    <None Remove="Protos\cus.proto" />
    <None Remove="Protos\generators.proto" />
    <None Remove="Protos\ous.proto" />
    <None Remove="Protos\plugins.proto" />
    <None Remove="Protos\services.proto" />
    <None Remove="Protos\system.proto" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Monq.Models.Abstractions" />
    <PackageReference Include="Google.Protobuf" />
    <PackageReference Include="Grpc.Net.Client" />
    <PackageReference Include="Grpc.Tools">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\PluginsCore\Hamstix.Haby.Shared.PluginsCore.csproj" />
  </ItemGroup>

  <ItemGroup>
    <SupportedPlatform Include="browser" />
  </ItemGroup>

  <ItemGroup>
    <Protobuf Include="Protos\configuration.proto" />
    <Protobuf Include="Protos\ous.proto" />
    <Protobuf Include="Protos\generators.proto" />
    <Protobuf Include="Protos\cus.proto" />
    <Protobuf Include="Protos\services.proto" />
    <Protobuf Include="Protos\plugins.proto" />
    <Protobuf Include="Protos\system.proto" />
  </ItemGroup>
</Project>
