<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
	<BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Fluid.Core" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Server" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
    <PackageReference Include="Mapster" />
    <PackageReference Include="Grpc.AspNetCore" />
    <PackageReference Include="Grpc.AspNetCore.Web" />
    <PackageReference Include="OpenTelemetry.Extensions.Hosting" />
    <PackageReference Include="OpenTelemetry.Instrumentation.AspNetCore" />
    <PackageReference Include="OpenTelemetry.Instrumentation.Http" />
    <PackageReference Include="OpenTelemetry.Instrumentation.Runtime" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Client\Hamstix.Haby.Client.csproj" />
    <ProjectReference Include="..\PluginsCore\Hamstix.Haby.Shared.PluginsCore.csproj" />
    <ProjectReference Include="..\Plugins\ArangoDb\Hamstix.Haby.Plugins.ArangoDb.csproj" />
    <ProjectReference Include="..\Plugins\ClickHouse\Hamstix.Haby.Plugins.ClickHouse.csproj" />
    <ProjectReference Include="..\Plugins\K8s_1_23\Hamstix.Haby.Plugins.K8s_1_23.csproj" />
    <ProjectReference Include="..\Plugins\PostgreSql12\Hamstix.Haby.Plugins.PostgreSql12.csproj" />
    <ProjectReference Include="..\Plugins\RabbitMQ\Hamstix.Haby.Plugins.RabbitMQ.csproj" />
    <ProjectReference Include="..\Shared\Hamstix.Haby.Shared.csproj" />
  </ItemGroup>

</Project>
