<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="IdentityServer4.EntityFramework" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\PluginsCore\Hamstix.Haby.Shared.PluginsCore.csproj" />
  </ItemGroup>

</Project>
